### ISSUE TITLE
cover unload/upgrade NIF callbacks

### ISSUE THREAD

**Issue by c-bik** [K2InformaticsGmbH/oranif#113]
![image](https://user-images.githubusercontent.com/913008/61116464-ca708e80-a494-11e9-89f9-527523191444.png)

**Comment by KarlKeiser** [comment]
covering the `unload` part may not be possible anymore:
![image](https://user-images.githubusercontent.com/42537965/61207009-4ae0fa80-a6f4-11e9-8021-eb0ec523fe0e.png)

**Comment by c-bik** [comment]
@KarlKeiser it seems erlang code purging is a sort of lazy algorithm.

## To invoke `unload`
```sh
$ ORANIF_DEBUG=100 rebar3 do clean, compile
$ erl -pa _build/default/lib/oranif/ebin
```
```erlang
% loading NIF first time
> dpi:load_unsafe().
{dpi,load_unsafe,61} priv not found
{dpi,load_unsafe,75} PrivDir ".../_build/default/lib/oranif/priv"
[c_src\dpi_nif.c:load:93] ->
[c_src\dpi_nif.c:load:110] <-
ok

% triggering unloading of NIF
> code:load_file(dpi).
{module,dpi}
> code:load_file(dpi).
{error,not_purged}
=ERROR REPORT==== 15-Jul-2019::17:25:32 ===
Loading of .../_build/default/lib/oranif/ebin/dpi.beam failed: not_purged
> code:purge(dpi).
[c_src\dpi_nif.c:unload:125] ->
[c_src\dpi_nif.c:unload:126] <-
false
```
## To invoke `upgrade`
Ref : http://erlang.org/pipermail/erlang-questions/2011-October/061467.html
> Load the new version of your module and let that new Erlang code load 
your new NIF library with erlang:load_nif/2. The callback 'upgrade' will 
then be called in your new library (instead of 'load") and that will 
give you opportunity to transfer state from your old library if you want 
to. The 'unload' callback will later be called in your old NIF library 
before the old version of your module is purged.

**Comment by c-bik** [comment]
Implemented https://github.com/K2InformaticsGmbH/oranif/pull/118
