### ISSUE TITLE
Support for 'DPI_MODE_EXEC_COMMIT_ON_SUCCESS' 

### ISSUE THREAD

**Issue by acautin** [K2InformaticsGmbH/oranif#127]
It would be helpful to be able to provide this mode when using `dpiStmt_execute` or `dpiStmt_executeMany` 

Ref: 

https://oracle.github.io/odpi/doc/enums/dpiExecMode.html#dpiexecmode

**Comment by c-bik** [comment]
@acautin 
Looks like the support is already in!
https://github.com/K2InformaticsGmbH/oranif/blob/a9ce0a1d070442d603f142ae5d4cfea920c1996b/c_src/dpiStmt_nif.h#L54-L61
Please give it a try and confirm.

**Comment by acautin** [comment]
Verified `DPI_MODE_EXEC_COMMIT_ON_SUCCESS` works as expected, thanks!
