### ISSUE TITLE
dpi:load/1 with atom with '.' in the slave node name results in timeout

### ISSUE THREAD

**Issue by shamis** [K2InformaticsGmbH/oranif#131]
```erlang
(test@WKS017)5> dpi:load(test3).
test3@WKS017
(test@WKS017)6> dpi:load('test3.test').
{error,timeout}
```

**Comment by c-bik** [comment]
@shamis It seems there are some un documented restriction of choosing erlang node names
[found in code comment](https://github.com/erlang/otp/blob/65449e9e54fd765abdbe546590e4da044f36c2a4/erts/emulator/beam/dist.c#L424-L434)
```c
/*
** A full node name consists of a "n@h"
**
** n must be a valid node name: string of ([a-z][A-Z][0-9]_-)+
** 
** h is not checked at all, we assume that we have a properly
** configured machine where the networking is ok for the OS
**
** We do check that there is not a second @ in the string, since
** many distributed operations are guaranteed not to work then.
*/
```
There is also an interesteing discussion as to why this isn't specified in erlang user manual [here](http://erlang.org/pipermail/erlang-questions/2008-June/035538.html)

So bottom line: Erlang doesn't support it. Closing!
