### ISSUE TITLE
Support for table types

### ISSUE THREAD

**Issue by shamis** [K2InformaticsGmbH/oranif#19]
In the example below `t_text_arr` is a table type used as an `in out` parameter for the procedure `test_proc`.

```sql
CREATE OR REPLACE TYPE "T_TEXT_ARR" AS
    TABLE OF VARCHAR2(4000);
```

```sql
CREATE OR REPLACE PROCEDURE test_proc ( p_text_arr IN OUT t_text_arr )
    IS
BEGIN
    p_text_arr(2) := 'world';
END test_proc;
```

```sql
DECLARE
    p_text   t_text_arr;
BEGIN
    p_text := t_text_arr('Hello','test');
    test_proc(
        p_text_arr   => p_text
    );
    dbms_output.put_line(p_text(1)
     || ' '
     || p_text(2) );

END;
```

**Comment by c-bik** [comment]
@KarlKeiser please verify / investigate support and report

**Comment by KarlKeiser** [comment]
Is is possible to do this. ODPI has an API called [Object Type](https://oracle.github.io/odpi/doc/functions/dpiObjectType.html) to do that. It says that "Object type handles are used to represent types such as those created by the SQL command CREATE OR REPLACE TYPE".

`CREATE OR REPLACE TYPE "T_TEXT_ARR" AS
    TABLE OF VARCHAR2(4000);` would be a normal SQL statement that is executed like any other statement, and then `dpiConn_getObjectType(Conn, "T_TEXT_ARR", strlen("T_TEXT_ARR"), &objTypeHandle);` would be called to get the object type.
