### ISSUE TITLE
dpi slave should be in hidden mode

### ISSUE THREAD

**Issue by shamis** [K2InformaticsGmbH/oranif#27]
slave node can be seen with `erlang:nodes()` and this is not ideal. This fun is used to do rpc multicall and should not hit the slave node

**Comment by c-bik** [comment]
Implemented: https://github.com/K2InformaticsGmbH/oranif/commit/31cdcb55a6bd41d7bb0667e60874f727ec551b85

**Comment by shamis** [comment]
thanks @c-bik. verified
