### ISSUE TITLE
Removed / Fix unused erlang macros

### ISSUE THREAD

**Issue by c-bik** [K2InformaticsGmbH/oranif#34]
Fix TODO
https://github.com/K2InformaticsGmbH/oranif/blob/842462d12347b37040191b8dc0a8b47ed1a03b5d/src/dpi.hrl#L21-L22
https://github.com/K2InformaticsGmbH/oranif/blob/842462d12347b37040191b8dc0a8b47ed1a03b5d/src/dpi.hrl#L29-L30

**Comment by KarlKeiser** [comment]
Was fixed when `odpi` got merged into `master`
