### ISSUE TITLE
Allow the possibility to create separated slave nodes.

### ISSUE THREAD

**Issue by acautin** [K2InformaticsGmbH/oranif#42]
It is possible the user of the library wants to have isolated environments for connections that are not related.

**Comment by stoch** [comment]
This means that the prefix of the slave node should be configured in the cpro job config (atom or binstr or string according to current standards).

Ultimately, a value like atom 'undefined' could mean that the driver should be called directly, without slave node (for performance optimisation/comparison with associated risk taken).

**Comment by c-bik** [comment]
Duplicate of #43

**Comment by c-bik** [comment]
> This means that the prefix of the slave node should be configured in the cpro job config (atom or binstr or string according to current standards).
> 
> Ultimately, a value like atom 'undefined' could mean that the driver should be called directly, without slave node (for performance optimisation/comparison with associated risk taken).

`cproJob` table will ONLY support `atom` for slave node name configuration!
