### ISSUE TITLE
dpi:unload/0 should stop the slave only if its the last process using the slave node

### ISSUE THREAD

**Issue by shamis** [K2InformaticsGmbH/oranif#53]
With the introduction of configurable node_name for the dpi_slave we cannot call `dpi:unload/0` if there are multiple processes using the same slave.

**Comment by c-bik** [comment]
Attempted / considered approaches so far...

approach|result
---|---
process get/set NIF API| `segfault` (re-investigate with mutex)
application environment get/set|concurrancy issues
ETS|owner process can't die
