### ISSUE TITLE
context_getError still being exported

### ISSUE THREAD

**Issue by KarlKeiser** [K2InformaticsGmbH/oranif#84]
The `dpi:context_getError` API is still being offered, however it shouldn't be used as the error messages are getting mangled. Instead, `dpiContext_getError` is being called internally just as an error happens, which then causes the function to throw the correct error message. This error message should be used rather than getting an error message by calling `dpiContext_getError`.

`dpi:context_getError` should be removed. Currently, one eunit testcase called `drop_nonexistent_table` still uses it.

**Comment by KarlKeiser** [comment]
fixed in branch `karl-eunit_cleanup_1`

**Comment by c-bik** [comment]
should be closed by PR merging

**Comment by c-bik** [comment]
Please branch/PR seperately to master

**Comment by c-bik** [comment]
Removed in https://github.com/K2InformaticsGmbH/oranif/commit/9412f9d66bb398e08264b708b97b1227c7eb83d8#diff-90afd8483b022beef28f6853c9ec7339
